### ISSUE TITLE
proxy integration

### ISSUE THREAD

**Issue by nmushegian** [makerdao/pymaker#29]
Everyone actively writing keepers should familiarize themselves with https://github.com/dapphub/ds-proxy

**Comment by reverendus** [comment]
I am quite aware of how `DSProxy` works and I have even considered using it in keepers, but I couldn't find any use-case for it.

I did find a usecase for a _"transaction manager"_ though (https://github.com/reverendus/tx-manager) for making multiple calls atomically in one Ethereum transaction, but I think we both agreed at some point that's it's something very specific to the keeper framework. I completely agree with it, although I would prefer to place that repo as `makerdao/keeper-tx-manager` instead of keeping it in my personal GitHub.

Of course I am open to suggestions, bear in mind that I have much less Ethereum development experience than you. Did you mean any specific use-cases for `ds-proxy`?

**Comment by nmushegian** [comment]
> Solidity contract to make multiple calls in one Ethereum transaction

this is my understanding of the function of ds-proxy so we should chat to catch up. The only difference is that proxy uses delegatecall to deployed code which saves on gas massively for repeated operations like for keepers. Your tx-manager is essentially one possible argument to ds-proxy.

**Comment by reverendus** [comment]
So if `tx-manager` bytecode should be a `ds-proxy` argument, what is the advantage of using `ds-proxy` comparing to simply deploying a `tx-manager` instance and calling it directly? Assuming of course that the `tx-manager` bytecode doesn't change, which is actually the case here.

**Comment by nmushegian** [comment]
Well theoretically code reuse among distinct tx-managers. But look at your statement, "what is the advantage of using `ds-proxy` compared to deploying a single `XYZ` instance and calling it directly?", is the same for EVERY xyz. Someone will make a clean generalization of this.

**Comment by nmushegian** [comment]
Even bigger advantage is:  Same identity between distinct scripts. When our hard-coded `tx-manager` interacts with many contracts its address is accessed via `msg.sender`. If you want a slightly different behavior you have to use a new account from the POV of the app you are using.

**Comment by reverendus** [comment]
`DSProxy` support has been added to `pymaker` some time ago already.
Closing.
