### ISSUE TITLE
`ImportError: cannot import name 'coerce_return_to_text'`

### ISSUE THREAD

**Issue by moskalyk** [makerdao/pymaker#59]
I was getting this error from the current version of Web3
`ImportError: cannot import name 'coerce_args_to_text'`

By updating to the pre-release: e.g. web3==4.0.0b11 it fixed the error, but then this opened up another error.

```

  File "../MakerDAO/pymaker/pymaker/util.py", line 23, in <module>
    from eth_utils import coerce_return_to_text, encode_hex
ImportError: cannot import name 'coerce_return_to_text'
```

**Comment by reverendus** [comment]
Unfortunately we do not support `web3.py` v4.x.x yet. The recommended version of `web3.py` is `3.16.4`, and this is the one referenced by the `requirements.txt` file.

We have also updated the `requirements.txt` file since you opened this issue, it now explicitly references some versions of the `web3.py` dependencies. If you install exactly these versions (`pip3 -r requirements.txt` should do the thing), problems like that should not happen anymore. If they still do, please reopen this issue and we will look into it.
